### ISSUE TITLE
Python3 does not know about unicode

### ISSUE THREAD

**Issue by mjuenema** [mantl/terraform.py#74]
```
 inventory/terraform_inventory.sh --list --noterraform
Traceback (most recent call last):
  File "/home/mjuenemann/.virtualenvs/playground3/bin/ati", line 11, in <module>
    load_entry_point('ati==0.4.4.dev0', 'console_scripts', 'ati')()
  File "/home/mjuenemann/.virtualenvs/playground3/lib/python3.5/site-packages/ati-0.4.4.dev0-py3.5.egg/ati/cli.py", line 81, in cli
    output = query_list(hosts)
  File "/home/mjuenemann/.virtualenvs/playground3/lib/python3.5/site-packages/ati-0.4.4.dev0-py3.5.egg/ati/terraform.py", line 945, in query_list
    for name, attrs, hostgroups in hosts:
  File "/home/mjuenemann/.virtualenvs/playground3/lib/python3.5/site-packages/ati-0.4.4.dev0-py3.5.egg/ati/terraform.py", line 106, in iterhosts
    for module_name, key, resource in resources:
  File "/home/mjuenemann/.virtualenvs/playground3/lib/python3.5/site-packages/ati-0.4.4.dev0-py3.5.egg/ati/terraform.py", line 55, in iterresources
    if type(source) in [unicode, str]:
NameError: name 'unicode' is not defined
```

**Comment by danlamanna** [comment]
Consider using something like `six.text_type` for this: https://pythonhosted.org/six/#six.text_type.

**Comment by mjuenema** [comment]
Thanks
